apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: netlifytrial-eb6t
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pshivpuj-tenant/netlifytrial-1/netlifytrial-eb6t@sha256:83cb7670cfab678aa0e11da656693857a0cdf650482ec4712cce80608340c5b9
        name: my-nodejs
        resources: {}
status: {}
